services:
  app:
    image: ${REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}
    build: .
    container_name: hydra-manager-bot
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongodb:27017/hydramanagerbot
      - HYDRA_BOT_TOKEN=${HYDRA_BOT_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./data:/data
    restart: always

  mongodb:
    image: mongo:7
    container_name: hydra-mongodb
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: hydra-redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongodb_data:
  redis_data:
