# fly.toml app configuration file generated for link-fixer-bot on 2025-03-19T01:31:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'link-fixer-bot'
primary_region = 'otp'

[build]
  dockerfile = 'Dockerfile'

[env]
  DOWNLOADS_DIR = '/data/downloads'

[[mounts]]
  source = 'downloads_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
