spring:
  application:
    name: hydra-manager-bot
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/hydramanagerbot}

logging:
  file:
    name: /data/logs/hydra-manager-bot.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: INFO
    com.mamoru: DEBUG
    org.springframework: INFO

telegram:
  bot:
    name: ${HydraManager_Bot}
    token: ${HYDRA_BOT_TOKEN}
