name: deploy.yml

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "IMAGE_REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "IMAGE_REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Create .env file
        run: |
          echo "REGISTRY=${{ env.REGISTRY }}" > .env
          echo "IMAGE_REPO=${{ env.IMAGE_REPO }}" >> .env
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> .env
          echo "BOT_TOKEN_1=${{ secrets.BOT_TOKEN_1 }}" >> .env
          echo "BOT_TOKEN_2=${{ secrets.BOT_TOKEN_2 }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,.env"
          target: "/opt/linkfixer/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Authenticate server with GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Ensure project directory exists
            sudo mkdir -p /opt/linkfixer/data/logs
            sudo chown -R $USER:$USER /opt/linkfixer
            
            # Change to project directory
            cd /opt/linkfixer

            # Create cookies.txt from secret
            echo "${{ secrets.COOKIES_CONTENT }}" > /opt/linkfixer/data/cookies.txt

            # Pull and restart services
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans